version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
      - save_cache:
          key: node-module-{{ checksum "mystring" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: node-module-{{ checksum "mystring" }}
      - run: npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: node-module-{{ checksum "mystring" }}
      - run: npm run audit
workflows:
  my_flow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
    